eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    ###  需要将服务注册到注册中心
    register-with-eureka: true
    ### 检索服务信息
    fetch-registry: true
### 服务启动端口号
server:
  port: 8100
##服务名称(服务注册到eureka名称)--服务注册到注册中心的名称
spring:
  application:
    name: eureka-client
# 监控配置
management:
  endpoints:
    web:
#     默认监控前缀
      base-path: /monitor
      exposure:
        # 包含端点
        include: "*"
  # 单个端点设置
  endpoint:
    shutdown:
      enabled: false
    info:
      head: ${spring.application.name}
      body: Welcome, this is ${spring.application.name} @ ${server.port}
