eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    ###  需要将服务注册到注册中心
    register-with-eureka: true
    ### 检索服务信息
    fetch-registry: true
### 服务启动端口号
server:
  port: 8100
##服务名称(服务注册到eureka名称)--服务注册到注册中心的名称
spring:
  application:
    name: eureka-client