eureka:
  client:
    service-url:
      ### 注册中心地址
      defaultZone: http://localhost:8000/eureka
    ###  需要将服务注册到注册中心
    register-with-eureka: true
    ### 检索服务信息
    fetch-registry: true
    # 注册区域，AWS使用
    region: ch-east-1
    healthcheck:
      # 健康检查 开启 启用客户端运行状况检查可以修改server端运行状态
      enabled: true
  instance:
    hostname: localhost
    # 主页下面三个参数，是客户端发布给服务端
    #  主界面
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    #    下面三个参数，是客户端发布给服务端
    # 配置状态监控页面
    #status-page-url: http://${eureka.instance.hostname:localhost}:${management.port:8088}${management.context-path:/monitor}${endpoints.info.path:/info}
    #status-page-url: http://${eureka.instance.hostname}:${management.server.port}${management.endpoints.web.base-path}/info
    # 配置健康监控页面
    #health-check-url: http://${eureka.instance.hostname}:${management.server.port}${management.endpoints.web.base-path}/health
    # 设置Instance ID
    # instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
# 服务名称(服务注册到eureka名称)--服务注册到注册中心的名称
spring:
  application:
    name: winning-service-oauth
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
  redis:
    host: 192.168.31.191
    database: 0
    password: 123456
# 监控配置
management:
  #server:
  # 监控服务页面端口
  #port: 8088
  endpoints:
    web:
      # 默认监控前缀
      #      base-path: /monitor
      exposure:
        # 包含端点
        include: "*"
  # 单个端点设置
  endpoint:
    shutdown:
      enabled: false
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    head: ${spring.application.name}
    body: Welcome, this is ${spring.application.name} @ ${server.port}
server:
  port: 9100
