server:
  port: 8700
eureka:
  client:
    service-url:
      ### 注册中心地址
      defaultZone: http://localhost:8000/eureka
    ###  需要将服务注册到注册中心
    register-with-eureka: true
    ### 检索服务信息
    fetch-registry: true
    # 注册区域，AWS使用
    region: ch-east-1
    healthcheck:
      # 健康检查 开启 启用客户端运行状况检查可以修改server端运行状态
      enabled: true
  instance:
    hostname: localhost
    # 主页下面三个参数，是客户端发布给服务端
    #  主界面
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
# 服务名称(服务注册到eureka名称)--服务注册到注册中心的名称
spring:
  application:
    name: zipkin-mysql-server
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# 监控配置
management:
  #server:
  # 监控服务页面端口
  #port: 8088
  endpoints:
    web:
      # 默认监控前缀
      #      base-path: /monitor
      exposure:
        # 包含端点
        include: "*"
  # 单个端点设置
  endpoint:
    shutdown:
      enabled: false
  # 解决zipkin server UI报错问题
  metrics:
    web:
      server:
        auto-time-requests: false
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    head: ${spring.application.name}
    body: Welcome, this is ${spring.application.name} @ ${server.port}
zipkin2:
  storage:
    type: mysql