server:
  port: 8765
spring:
  application:
    name: consul-customer
  cloud:
    consul:
      host: 192.168.31.59
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        tags: version=1.0,author=winning devops, ${spring.application.name}
        register: true
        hostname: 102.168.31.59
        health-check-interval: 5s
        health-check-url: http://${spring.cloud.consul.discovery.hostname}:${server.port}/actuator/health
        health-check-path: /actuator/health
  boot:
    admin:
      client:
        url: http://192.168.31.59:9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
