server:
  port: 8765
spring:
  application:
    name: consul-customer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: consul-customer
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
