server:
  # 端口
  port: 8001
eureka:
  instance:
    hostname: peer2
  client:
    # 本身为注册中心，不需要去检索服务信息
    register-with-eureka: false
    # 本身为注册中心，是否需要在注册中心注册，默认true  集群设置为true
    fetch-registry: true
  dashboard:
    path: /eureka/server
spring:
  application:
    name: eureka-server-peer2
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
