server:
  port: 8900
eureka:
  client:
    service-url:
      ### 注册中心地址
      defaultZone: http://localhost:8000/eureka
    ###  需要将服务注册到注册中心
    register-with-eureka: true
    ### 检索服务信息
    fetch-registry: true
    # 注册区域，AWS使用
    region: ch-east-1
    healthcheck:
      # 健康检查 开启 启用客户端运行状况检查可以修改server端运行状态
      enabled: true
  instance:
    hostname: localhost
    # 主页下面三个参数，是客户端发布给服务端
    #  主界面
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
# 服务名称(服务注册到eureka名称)--服务注册到注册中心的名称
spring:
  application:
    name: gateway-rabbitmq-service
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
# sleuth 传输到RabbitMQ的时候使用
  rabbitmq:
    host: 192.168.31.187
    port: 5672
    username: chensj
    password: 123456
  sleuth:
    sampler:
      # 链路上传的概率
      probability: 1.0
      percentage: 1.0
# 监控配置
management:
  #server:
  # 监控服务页面端口
  #port: 8088
  endpoints:
    web:
      # 默认监控前缀
      #      base-path: /monitor
      exposure:
        # 包含端点
        include: "*"
  # 单个端点设置
  endpoint:
    shutdown:
      enabled: false
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    head: ${spring.application.name}
    body: Welcome, this is ${spring.application.name} @ ${server.port}
zuul:
  routes:
    hiapi:
      path: /user-api/**
      serviceId: user-rabbitmq-service
  # 设置超时时间
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 500
# 配置失效时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
