server:
  port: 8500
eureka:
  client:
    service-url:
      ### 注册中心地址
      defaultZone: http://localhost:8000/eureka
    ###  需要将服务注册到注册中心
    register-with-eureka: true
    ### 检索服务信息
    fetch-registry: true
    # 注册区域，AWS使用
    region: ch-east-1
    healthcheck:
      # 健康检查 开启 启用客户端运行状况检查可以修改server端运行状态
      enabled: true
  instance:
    hostname: localhost
    # 主页下面三个参数，是客户端发布给服务端
    #  主界面
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
#    下面三个参数，是客户端发布给服务端
    # 配置状态监控页面
    #status-page-url: http://${eureka.instance.hostname:localhost}:${management.port:8088}${management.context-path:/monitor}${endpoints.info.path:/info}
    #status-page-url: http://${eureka.instance.hostname}:${management.server.port}${management.endpoints.web.base-path}/info
    # 配置健康监控页面
    #health-check-url: http://${eureka.instance.hostname}:${management.server.port}${management.endpoints.web.base-path}/health
    # 设置Instance ID
    # instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
# 服务名称(服务注册到eureka名称)--服务注册到注册中心的名称
spring:
  application:
    name: eureka-zuul
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
# 监控配置
management:
  #server:
    # 监控服务页面端口
    #port: 8088
  endpoints:
    web:
      # 默认监控前缀
#      base-path: /monitor
      exposure:
        # 包含端点
        include: "*"
  # 单个端点设置
  endpoint:
    shutdown:
      enabled: false
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    head: ${spring.application.name}
    body: Welcome, this is ${spring.application.name} @ ${server.port}
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign
  # 版本号 访问的地址就是 http://localhost:8500/v1/hiapi/hi/admin
  prefix: /v1
  # 设置超时时间
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 500
#熔断机制超时
hystrix:
  command:
    default:
      excution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeout-in-milliseconds: 60000
#    使用默认的熔断器处理请求问题
    hiapi:
      excution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeout-in-milliseconds: 60000
    ribbonapi:
      excution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeout-in-milliseconds: 60000
    feignapi:
      excution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeout-in-milliseconds: 60000
# 配置失效时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#    hiapi-v:
#      path: /hiapiv/**
#      serviceId: hiapi-v
## 在指定url的时候，还需要使用负载均衡的时候，那么就需要自己维护负载均衡注册列表
## 将ribbon.eureka.enabled 改为 false
#ribbon:
#  eureka:
#    enabled: false
## 配置负载均衡的url
#hiapi-v:
#  ribbon:
#    listOfServers: http://localhost:8101,http://localhost:8102

