server:
  port: 9101
eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      ### 注册中心地址
      defaultZone: http://localhost:8000/eureka
    ###  需要将服务注册到注册中心
    register-with-eureka: true
    ### 检索服务信息
    fetch-registry: true
    # 注册区域，AWS使用
    region: ch-east-1
    healthcheck:
      # 健康检查 开启 启用客户端运行状况检查可以修改server端运行状态
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    #添加eureka.instance.metadata-map.user.name和eureka.instance.metadata-map.user.name 否则在安全模式下无法注册
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    hostname: localhost
    # 主页下面三个参数，是客户端发布给服务端
    #  主界面
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
# 服务名称(服务注册到eureka名称)--服务注册到注册中心的名称
spring:
  application:
    name: admin-client-one
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
#  security.user.name和security.user.password是访问admin-server的权限
  security:
    user:
      name: "admin"
      password: "admin"
# 监控配置
management:
  #server:
    # 监控服务页面端口
    #port: 8088
  endpoints:
    web:
      # 默认监控前缀
#      base-path: /monitor
      exposure:
        # 包含端点
        include: "*"
  # 单个端点设置
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    head: ${spring.application.name}
    body: Welcome, this is ${spring.application.name} @ ${server.port}
logging:
  file: "logs/admin-client-one-sample.log"
