# 自定义属性
my:
  name: demo
  age: 20
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm ${my.name}
# 多环境参数设置
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update # update 自动更新表结构 create 存在则删除重新创建
    show-sql: true # 显示SQL
#  redis 参数
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    #redis配置结束
    blockwhenexhausted: true
# 运行状态监控
management:
#  服务端口
#  server:
#    port: 9090
  endpoints:
#    web访问的路径前缀
    web:
      base-path: /monitor
#      设置web情况下暴露的端点
      exposure:
        include: '*'
# 单个端点设置
  endpoint:
#    关闭系统端点禁止使用
    shutdown:
      enabled: false
#   显示详细的健康信息
    health:
      show-details: always
  security:
    enabled: false



