# 自定义属性
my:
  name: demo
  age: 20
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm ${my.name}
# 多环境参数设置
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update # update 自动更新表结构 create 存在则删除重新创建
    show-sql: true # 显示SQL
# 运行状态监控
management:
#  服务端口
#  server:
#    port: 9090
  endpoints:
#    web访问的路径前缀
    web:
      base-path: /monitor
#      设置web情况下暴露的端点
      exposure:
        include: '*'
# 单个端点设置
  endpoint:
#    关闭系统端点禁止使用
    shutdown:
      enabled: false
#   显示详细的健康信息
    health:
      show-details: always
  security:
    enabled: false


