eureka:
  client:
    healthcheck:
      # 健康检查 开启 启用客户端运行状况检查可以修改server端运行状态
      enabled: true
### 服务启动端口号
server:
  port: 8200
# 服务名称(服务注册到eureka名称)--服务注册到注册中心的名称
spring:
  application:
    name: eureka-hystrix
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
# 监控配置
management:
  server:
    # 监控服务页面端口
    port: 8288
  endpoints:
    web:
      # 默认监控前缀
      base-path: /monitor
      exposure:
        # 包含端点
        include: "*"
  # 单个端点设置
  endpoint:
    shutdown:
      enabled: false
    info:
      head: ${spring.application.name}
      body: Welcome, this is ${spring.application.name} @ ${server.port}
